on: pull_request

env:
  NODE_VERSION: '12.x'

jobs:
  deploy-develop:
    name: "Build and deploy to S3 and purge CloudFront cache"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: "Compile Sass"
        run: yarn compile:sass
      - name: "Build application"
        run: yarn build
      - name: "check for vulnerabilities"
        run: /bin/sh -c 'yarn audit --level high; [[ $? -ge 8 ]] && exit 1 || exit 0'
